changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Documentation Enhancements
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"